// Generates dist/_headers (security + caching headers) AFTER `vite build`.
// Cloudflare Workers Static Assets parses _headers from the assets directory
// and applies it to responses: https://developers.cloudflare.com/workers/static-assets/headers/
//
// The Content-Security-Policy needs to allow the inline theme script in
// index.html (it prevents a flash of the wrong theme before React hydrates).
// Rather than 'unsafe-inline' (which would weaken script-src) or a hardcoded
// hash (which is line-ending- and build-dependent), we hash whatever inline
// scripts the build actually produced — so the CSP is always correct for the
// current dist/, on any OS / CI.
import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const dist = resolve(dirname(fileURLToPath(import.meta.url)), "..", "dist");
const html = readFileSync(resolve(dist, "index.html"), "utf8");

// sha256-<base64> for every inline <script> (those without a src attribute).
const inlineScriptHashes = [
  ...html.matchAll(/<script(?![^>]*\ssrc=)[^>]*>([\s\S]*?)<\/script>/g),
].map((m) => `'sha256-${createHash("sha256").update(m[1], "utf8").digest("base64")}'`);

const csp = [
  "default-src 'self'",
  `script-src 'self' ${inlineScriptHashes.join(" ")}`.trim(),
  // 'unsafe-inline' is required for Framer Motion's inline style attributes;
  // fonts.googleapis.com serves the Google Fonts stylesheet.
  "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
  "font-src 'self' https://fonts.gstatic.com",
  "img-src 'self' data:",
  "connect-src 'self'",
  "frame-ancestors 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "object-src 'none'",
  "upgrade-insecure-requests",
].join("; ");

const headers = `# Generated by scripts/generate-headers.mjs — do not edit by hand.
/*
  Content-Security-Policy: ${csp}
  Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=(), interest-cohort=()
  Cross-Origin-Opener-Policy: same-origin
  X-XSS-Protection: 0

# Content-hashed build assets are safe to cache forever.
/assets/*
  Cache-Control: public, max-age=31536000, immutable
`;

writeFileSync(resolve(dist, "_headers"), headers, "utf8");
console.log(`Generated dist/_headers (${inlineScriptHashes.length} inline-script hash(es))`);
